<?php
/**
 * @var \Inchoo\ProductBookmark\Block\Bookmark\Bookmark $block
 */
$bookmarkLists = $block->getBookmarkLists();
if ($block->isLoggedIn() && !empty($bookmarkLists)) :
?>
<div class="product-addto-links">
<form id = "addtobookmark" action="<?= $block->escapeHtml($block->getAction()) ?>" method="post">

    <input type="hidden" id="productId" name="productId">
    <input class="action submit primary" type="submit" value="Bookmark">
    <select style="max-width: 50%" name="list" data-toggle="dropdown">
        <?php foreach ($bookmarkLists as $bookmarkList) :?>
        <option value="<?=$bookmarkList->getId()?>"><?= $block->escapeHtml($bookmarkList->getTitle())?></option>
    <?php endforeach; ?>
    </select>

</form><br>
</div>
<?php endif; ?>
