<?php
/**
 * @var \Inchoo\ProductBookmark\Block\BookmarkList\BookmarkList $block
 */
?>
<h3>Create New Bookmark List</h3>
<form action="<?php echo $block->getFormAction() ?>" method="post">
    <label for="title">Name</label>
    <input class="textarea-example-1" name="title" type="text">
    <input class="action subscribe primary" type="submit" value="Submit">
</form>

<h3>My Bookmark Lists:</h3><br>
<ul class="list">
    <?php foreach ($block->getBookmarkLists() as $bookmarkList): ?>
    <li><a href="<?= $block->getBookmarkListById($bookmarkList->getId())?>"><?= $bookmarkList->getTitle() ?></a></li>


<?php endforeach; ?>

</ul>
