<?php
/**
 * @var \Magento\Catalog\Model\Product $product
 * @var \Inchoo\ProductBookmark\Block\BookmarkList\BookmarkListDetails $block
 */
if ($block->getProductCollection()) {
    foreach ($block->getProductCollection() as $product): ?>

        <a href="<?= $block->escapeUrl($product->getProductUrl()); ?>"><img src="<?= $block->escapeUrl($block->getImage($product, 'product_base_image')) ?>"/></a><br>
        <p><?= $block->escapeHtml($product->getName()); ?></p>

<?php endforeach;
} else {
    echo "No products.";
}
?>
