<?php
/**
* @var \Inchoo\ProductBookmark\Block\Bookmark\Bookmark $block
 */

if ($block->isLoggedIn()):
?>
<div class="product-addto-links">
<form action="<?php echo $block->getAction() ?>" method="post">

    <input type="hidden" id="productId" name="productId" value="<?= $block->escapeHtml($block->getProductId())?>">
    <input class="action submit primary" type="submit" value="Bookmark">
    <select style="max-width: 50%" name="list" data-toggle="dropdown">
        <?php foreach ($block->getBookmarkLists() as $bookmarkList):?>
        <option value="<?=$bookmarkList->getId()?>"><?= $block->escapeHtml($bookmarkList->getTitle())?></option>
    <?php endforeach; ?>
    </select>

</form><br>
</div>
<?php endif; ?>